name: Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:      
      - uses: ros-tooling/setup-ros@v0.6
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: map_cover
          target-ros2-distro: humble
          vcs-repo-file-url: https://github.com/halehaka/map_cover.git
          
